# Generated by Django 5.1.2 on 2024-10-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like_unique_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_likes',
            field=models.BooleanField(default=True),
        ),
    ]
