# Generated by Django 5.1.2 on 2024-10-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_like_comment_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
