# Generated by Django 5.1.2 on 2024-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_content_en_post_content_ru_post_content_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
