# Generated by Django 5.1.2 on 2024-11-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_comment_like_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
