services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:  
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A conf worker --loglevel=info
    volumes:
    - .:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:      
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A conf beat --loglevel=info
    volumes:
    - .:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:      
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: