# Generated by Django 5.1.2 on 2024-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
