# Generated by Django 5.1.2 on 2024-10-23 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_connections', related_query_name='following_connection', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_connections', related_query_name='follower_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
