# Generated by Django 5.1.2 on 2024-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountconnection'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountconnection',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_connection'),
        ),
    ]
