# Generated by Django 5.1.2 on 2024-10-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountconnection_unique_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconnection',
            name='is_request_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
